services:
  - type: web
    name: RAG-Based-Chatbot-System
    runtime: docker
    repo: https://github.com/vis-hal-git/RAG-Based-Chatbot-System
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false

